sudo: required
language: common-lisp

os:
  - linux
  - osx

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;
  - cl -e '(ql-util:without-prompting (ql:add-to-init-file))'

script:
  - cl -l cffi -f $TRAVIS_BUILD_DIR/tests/travis.lisp
